# This file defines the menus on the website. See the documentation for
# details: http://docs.bolt.cm/menus

main:
  - label: Home
    title: This is the first menu item.
    path: homepage
#    class: first
  - label: Features
    path: page/features
  - label: Documentation
    link: http://docs.bolt.cm
  - label: News
    path: page/news
  - label: Showcase
    path: page/showcase
  - label: Community [IRC/Slack/Forum]
    path: pages/community
  - label: Download
    path: pages/download
#    class: last
